//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPalma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Habitacion()
        {
            this.Reservas = new HashSet<Reserva>();
        }
    
        public int id_habitacion { get; set; }
        public int numero_habitacion { get; set; }
        public bool activo { get; set; }
        public decimal precio { get; set; }
        public int tipo_vista { get; set; }
        public int id_hotel { get; set; }
        public int id_tipo_habitacion { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Tipo_Habitacion Tipo_Habitacion { get; set; }
        public virtual Tipo_Vista Tipo_Vista1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reservas { get; set; }
    }
}
