//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPalma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int id_pago { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public decimal monto_total { get; set; }
        public string estado_pago { get; set; }
        public string referencia { get; set; }
        public int id_metodo_pago { get; set; }
        public int id_reserva { get; set; }
    
        public virtual Metodo_Pago Metodo_Pago { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
