//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPalma.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor_Producto
    {
        public int id_proveedor_producto { get; set; }
        public int id_proveedor { get; set; }
        public int id_producto { get; set; }
        public decimal precio_unitario { get; set; }
        public int cantidad_producto { get; set; }
        public int id_hotel { get; set; }
        public bool activo { get; set; }

        [JsonIgnore]
        public virtual Hotel Hotel { get; set; }
        [JsonIgnore]
        public virtual Producto Producto { get; set; }
        [JsonIgnore]
        public virtual Proveedor Proveedor { get; set; }
    }
}
