//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPalma.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.CheckIns = new HashSet<CheckIn>();
            this.CheckOuts = new HashSet<CheckOut>();
            this.Pagoes = new HashSet<Pago>();
        }
    
        public int id_reserva { get; set; }
        public Nullable<System.DateTime> fecha_reserva { get; set; }
        public System.DateTime fecha_llegada { get; set; }
        public System.DateTime fecha_salida { get; set; }
        public int numero_huespedes { get; set; }
        public string observaciones { get; set; }
        public bool activo { get; set; }
        public string documento_cliente { get; set; }
        public int id_habitacion { get; set; }
        public Nullable<int> id_paquete { get; set; }
        public int Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<CheckIn> CheckIns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<CheckOut> CheckOuts { get; set; }
        [JsonIgnore]
        public virtual Cliente Cliente { get; set; }
        [JsonIgnore]
        public virtual Habitacion Habitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Pago> Pagoes { get; set; }
        [JsonIgnore]
        public virtual Paquete Paquete { get; set; }
        [JsonIgnore]
        public virtual Estado_Reserva Estado_Reserva { get; set; }
    }
}
