//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPalma.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public int id_servicio { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public bool activo { get; set; }
        public int id_hotel { get; set; }
        public int id_tipoServicio { get; set; }

        [JsonIgnore]
        public virtual Hotel Hotel { get; set; }
        [JsonIgnore]
        public virtual TipoServicio TipoServicio { get; set; }
    }
}
