//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPalma.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public int id_telefono { get; set; }
        public string numero { get; set; }
        public int id_tipo_telefono { get; set; }
        public string tipo_duenio { get; set; }
        public string id_duenio { get; set; }
        public bool activo { get; set; }

        [JsonIgnore]
        public virtual Tipo_Telefono Tipo_Telefono { get; set; }
    }
}
